### ISSUE TITLE
Minecraft crash on world loading

### ISSUE THREAD

**Issue by JohnMidnight80** [OpenMods/OpenBlocks#1030]
Hello, I just installed OpenBlocks and OpenModsLib, but when I load or create a world it crashes. I have the 1.12.2 version, here is the crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  SmartMovingPlugin (SmartMovingReloaded-1.12.2-0.0.4.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 12/19/20 11:47 AM
Description: Unexpected error

java.lang.NoSuchFieldError: playerState
	at net.minecraft.client.entity.EntityPlayerSP.func_70093_af(EntityPlayerSP.java:1339)
	at net.minecraft.entity.player.EntityPlayer.func_70047_e(EntityPlayer.java:2307)
	at net.minecraft.entity.Entity.func_174824_e(Entity.java:1573)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:65)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:49)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_144_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.entity.EntityPlayerSP.func_70093_af(EntityPlayerSP.java:1339)
	at net.minecraft.entity.player.EntityPlayer.func_70047_e(EntityPlayer.java:2307)
	at net.minecraft.entity.Entity.func_174824_e(Entity.java:1573)
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:65)
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:49)
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_144_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['John_Midnight'/4283, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['John_Midnight'/4283, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 642062296 bytes (612 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version           | Source                                        | Signature                                |
	|:------ |:-------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft            | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                  | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | openmodscore         | 0.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | jei                  | 4.16.1.302        | jei_1.12.2-4.16.1.302.jar                     | None                                     |
	| LCHIJA | appleskin            | 1.0.14            | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCHIJA | backpack             | 3.0.2             | backpack-3.0.2-1.12.2.jar                     | None                                     |
	| LCHIJA | bno                  | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.5.0.jar            | None                                     |
	| LCHIJA | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | bookshelf            | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftlib        | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftcore       | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders   | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcrafttransport  | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon    | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftenergy     | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | ic2                  | 2.8.221-ex112     | industrialcraft-2-2.8.221-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | forestry             | 5.8.2.387         | forestry_1.12.2-5.8.2.387.jar                 | None                                     |
	| LCHIJA | buildcraftcompat     | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftfactory    | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics   | 7.99.24.7         | buildcraft-all-7.99.24.7.jar                  | None                                     |
	| LCHIJA | cqrepoured           | 2.1.3B            | Chocolate_Quest_Repoured-1.12.2-2.1.3B.jar    | None                                     |
	| LCHIJA | codechickenlib       | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | comforts             | 1.4.1.2           | comforts-1.12.2-1.4.1.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCHIJA | cookingforblockheads | 6.4.71            | CookingForBlockheads_1.12.2-6.4.71.jar        | None                                     |
	| LCHIJA | customspawner        | 3.11.4            | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| LCHIJA | mocreatures          | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| LCHIJA | eplus                | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | enderstorage         | 2.4.6.137         | EnderStorage-1.12.2-2.4.6.137-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | fluxnetworks         | 4.0.14            | fluxnetworks-1.12.2-4.0.14-31.jar             | None                                     |
	| LCHIJA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                   | None                                     |
	| LCHIJA | ironchest            | 1.12.2-7.0.67.844 | Iron-Chests-Mod-1.12.2.jar                    | None                                     |
	| LCHIJA | journeymap           | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                   | None                                     |
	| LCHIJA | mantle               | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | naturescompass       | 1.8.0             | NaturesCompass-1.12.2-1.8.0.jar               | None                                     |
	| LCHIJA | openmods             | 0.12.2            | OpenModsLib-1.12.2-0.12.2.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks           | 1.8.1             | OpenBlocks-1.12.2-1.8.1.jar                   | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | harvestcraft         | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zg.jar               | None                                     |
	| LCHIJA | projecte             | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                   | None                                     |
	| LCHIJA | thaumcraft           | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | railcraft            | 12.0.0            | railcraft-12.0.0.jar                          | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | reforged             | 0.7.5             | Reforged-Mod-1.12.jar                         | None                                     |
	| LCHIJA | simplyjetpacks       | 1.12.2-2.2.17.0   | SimplyJetpacks2-1.12.2-2.2.17.0.jar           | None                                     |
	| LCHIJA | smartmoving          | 0.0.4             | SmartMovingReloaded-1.12.2-0.0.4.jar          | None                                     |
	| LCHIJA | tconstruct           | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | treechopper          | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| LCHIJA | llibrary             | 1.7.20            | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SmartMovingPlugin (SmartMovingReloaded-1.12.2-0.0.4.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003' Renderer: 'Radeon RX 570 Series'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Radeon RX 570 Series GL version 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14757 Compatibility Profile Context 20.11.2 27.20.14501.18003
	OpenGlRenderer: Radeon RX 570 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4
```

Thanks in advance.

**Comment by boq** [comment]
Does not seem like Open Blocks issue, field `playerState` is supposed to be added by SmartMovingReloaded.

**Comment by JohnMidnight80** [comment]
It works now, thanks.
