### ISSUE TITLE
Afat error occured, this connection is terminated on opening OpenBlocks info book.

### ISSUE THREAD

**Issue by mrdeadlocked** [OpenMods/OpenBlocks#622]
We are on openblocks-1.7.10-1.3.jar when this happens. This on on a SMP server. If you need anything else let me know.

```
[10:24:33] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML
java.lang.NullPointerException: No items in grid
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-16.0.jar:?]
	at openmods.gui.component.GuiComponentCraftingGrid.<init>(GuiComponentCraftingGrid.java:27) ~[GuiComponentCraftingGrid.class:?]
	at openmods.gui.component.page.StandardRecipePage.<init>(StandardRecipePage.java:29) ~[StandardRecipePage.class:?]
	at openmods.gui.component.page.StandardRecipePage.<init>(StandardRecipePage.java:45) ~[StandardRecipePage.class:?]
	at openmods.infobook.PageBuilder.addPage(PageBuilder.java:90) ~[PageBuilder.class:?]
	at openmods.infobook.PageBuilder.addPages(PageBuilder.java:68) ~[PageBuilder.class:?]
	at openmods.infobook.PageBuilder.addItemPages(PageBuilder.java:98) ~[PageBuilder.class:?]
	at openmods.infobook.PageBuilder.addItemPages(PageBuilder.java:102) ~[PageBuilder.class:?]
	at openblocks.client.gui.GuiInfoBook.createRoot(GuiInfoBook.java:95) ~[GuiInfoBook.class:?]
	at openmods.gui.ComponentGui.<init>(ComponentGui.java:19) ~[ComponentGui.class:?]
	at openblocks.client.gui.GuiInfoBook.<init>(GuiInfoBook.java:34) ~[GuiInfoBook.class:?]
	at openblocks.OpenBlocksGuiHandler.getClientGuiElement(OpenBlocksGuiHandler.java:68) ~[OpenBlocksGuiHandler.class:?]
	at openmods.gui.ClientGuiHandler.getClientGuiElement(ClientGuiHandler.java:22) ~[ClientGuiHandler.class:?]
	at cpw.mods.fml.common.network.NetworkRegistry.getLocalGuiContainer(NetworkRegistry.java:263) ~[NetworkRegistry.class:?]
	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:93) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2209) ~[yz.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:16) ~[OpenGuiHandler.class:?]
	at cpw.mods.fml.common.network.internal.OpenGuiHandler.channelRead0(OpenGuiHandler.java:11) ~[OpenGuiHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
```

**Comment by boq** [comment]
#592 duplicate
