### ISSUE TITLE
Fatal Error after server restarts

### ISSUE THREAD

**Issue by Allalous** [OpenMods/OpenBlocks#696]
Me and my group of friends play on a custom modpack and for some reason we are getting this type of error when we try to login.

[16:37:54] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel OpenMods|I
java.lang.IllegalArgumentException: value already present: 5
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238) ~[guava-17.0.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215) ~[guava-17.0.jar:?]
	at openmods.network.rpc.MethodIdRegistry.entry(MethodIdRegistry.java:81) ~[MethodIdRegistry.class:?]
	at openmods.network.rpc.MethodIdRegistry.entry(MethodIdRegistry.java:17) ~[MethodIdRegistry.class:?]
	at openmods.datastore.DataStore.visit(DataStore.java:21) ~[DataStore.class:?]
	at openmods.datastore.DataStoreWrapper.notifyVisitors(DataStoreWrapper.java:35) ~[DataStoreWrapper.class:?]
	at openmods.datastore.DataStoreWrapper.activateData(DataStoreWrapper.java:40) ~[DataStoreWrapper.class:?]
	at openmods.datastore.DataStoreReader.read(DataStoreReader.java:38) ~[DataStoreReader.class:?]
	at openmods.network.IdSyncManager.decodeIds(IdSyncManager.java:116) ~[IdSyncManager.class:?]
	at openmods.network.IdSyncManager.access$000(IdSyncManager.java:29) ~[IdSyncManager.class:?]
	at openmods.network.IdSyncManager$InboundHandler.channelRead0(IdSyncManager.java:41) ~[IdSyncManager$InboundHandler.class:?]
	at openmods.network.IdSyncManager$InboundHandler.channelRead0(IdSyncManager.java:34) ~[IdSyncManager$InboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by boq** [comment]
You have mentioned restarts in title. Can you explain, what you meant?

Also, can you add information about versions of OpenBlocks and OpenModsLib (preferably on client AND server)?

**Comment by boq** [comment]
Any extra information about this one?

**Comment by tacusin** [comment]
what's the importance of the OpenBlocks and OpenModsLib versions?

**Comment by boq** [comment]
That's very weird question. Without version information most bug reports are useless. Especially ones that can't be easily reproduced.
