### ISSUE TITLE
Multiplayer Console Throws Up Java Exception Whenever Someone Tries to Restore Items from a Grave

### ISSUE THREAD

**Issue by Wealthyturtle** [OpenMods/OpenBlocks#802]
The Multiplayer Console Throws Up a Java Exception Whenever Someone Tries to Restore Items from a Grave.

Java Exception:
java.lang.NullPointerException
at openblocks.common.PlayerInventoryStore.restoreInventory(PlayerInventoryStore.java:274) ~[PlayerInventoryStore.class:?]
at openblocks.common.CommandInventory.func_71515_b(CommandInventory.java:75) [CommandInventory.class:?]
at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:99) [z.class:?]
at org.bukkit.craftbukkit.v1_7_R4.command.CraftSimpleCommandMap.dispatch(CraftSimpleCommandMap.java:53) [CraftSimpleCommandMap.class:1.7.10-1614.57]
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchVanillaCommand(CraftServer.java:756) [CraftServer.class:1.7.10-1614.57]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1377) [nh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by boq** [comment]
Can you post exact command you are using?

**Comment by RaresKool** [comment]
`/ob_inventory restore username restorefile`
Example `/ob_inventory restore RaresKool RaresKool-2016-11-17_09.03.10-death-0`

**Comment by boq** [comment]
Ok, can you now check if file `[server dir]/world/data/inventory-RaresKool-2016-11-17_09.03.10-death-0.dat`  or `[client dir]/saves/[world name]/data/inventory-RaresKool-2016-11-17_09.03.10-death-0.dat` exists? And if possible, post it somewhere, so I can inspect it?
