### ISSUE TITLE
Incompatible with optifine

### ISSUE THREAD

**Issue by essem2** [OpenMods/OpenBlocks#831]
Crash on startup when installing openblocks & openmodslib with optifine:

Optifine version: OptiFine_1.10.2_HD_U_D8
OpenModsLib: OpenModsLib-1.10.2-0.10-1.10.X-snapshot-45
OpenBlocks: OpenBlocks-1.10.2-1.6-1.10.X-snapshot-48
Forge: 1.10.2-forge1.10.2-12.18.3.2185

```// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 17.07.17 21:34
Description: Stitching texture atlas

java.lang.NullPointerException: Stitching texture atlas
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:325)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:354)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:154)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:325)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:181)

-- Texture being stitched together --
Details:
	Atlas path: textures
	Sprite: TextureAtlasSprite{name='openblocks:items/stencil-primer', frameCount=1, rotated=false, x=3056, y=448, height=16, width=16, u0=0.7460962, u1=0.74999756, v0=0.21875489, v1=0.22655761}
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:354)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:154)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by boq** [comment]
Sorry, due to extensive changes in render engine and closed source, we are not supporting Optifine - they have to support us.
