### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by DAmnshaYmZ** [OpenMods/OpenBlocks#841]
Hello, glad to see this coming to 1.10.2!

I have the following crash occuring when using Optifine 1.10.2_HD_U_E3 (the previous OF release was tested as well), OpenBlocks 1.10.2-1.7/OpenBlocksLib 1.10.2-0.11 .  No other mods installed.

MC 1.10.2 with Forge 12.18.3.2422 (no other versions of Forge tested):

![image](https://user-images.githubusercontent.com/30279542/28755005-8db81180-751f-11e7-8e56-3576cc79fa4b.png)

<details> 
  <summary>Crash report.</summary>
   <p>---- Minecraft Crash Report ----

WARNING: coremods are present:
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 7/30/17 11:36 AM
Description: Stitching texture atlas

java.lang.NullPointerException: Stitching texture atlas
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:325)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:354)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:154)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:325)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:181)

-- Texture being stitched together --
Details:
	Atlas path: textures
	Sprite: TextureAtlasSprite{name='openblocks:items/stencil-primer', frameCount=1, rotated=false, x=1008, y=400, height=16, width=16, u0=0.9843848, u1=0.9999902, v0=0.78126955, v1=0.81248045}
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:354)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:154)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1023478552 bytes (976 MB) / 1612709888 bytes (1538 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2422 Optifine OptiFine_1.10.2_HD_U_E3 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJA	Forge{12.18.3.2422} [Minecraft Forge] (forge-1.10.2-12.18.3.2422.jar) 
	UCHIJA	openmodscore{0.11} [OpenModsLib Core] (minecraft.jar) 
	UCHIJA	openmods{0.11} [OpenModsLib] (OpenModsLib-1.10.2-0.11.jar) 
	UCHIJA	openblocks{1.7} [OpenBlocks] (OpenBlocks-1.10.2-1.7.jar) 
	Loaded coremods (and transformers): 
OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 980 Ti/PCIe/SSE2'
	OpenModsLib class transformers: [pre_world_render_hook:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:ENABLED],[player_render_hook:FINISHED]
	Launched Version: forge-12.18.3.2422
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.76, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 384.76
	OpenGlRenderer: GeForce GTX 980 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8.</p> 
</details>

Thanks!

**Comment by boq** [comment]
#839, #835, #831 duplicate. Optifine issue: https://github.com/sp614x/optifine/issues/787
