### ISSUE TITLE
Mod crash during Model-loadingscreen

### ISSUE THREAD

**Issue by 0Chris0** [OpenMods/OpenBlocks#843]
And yes, I have the newest Version of Open -Blocks/-ModsLib for 1.10.2. Crash Report:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.1.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.7.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  AstralCore (astralsorcery-1.3.2-beta.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 09.08.17 13:00
Description: Stitching texture atlas

java.lang.NullPointerException: Stitching texture atlas
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:325)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:343)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:146)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.nio.DirectIntBufferU.put(DirectIntBufferU.java:357)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110994_a(TextureUtil.java:325)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147947_a(TextureUtil.java:197)
	at net.minecraft.client.renderer.texture.TextureUtil.func_147955_a(TextureUtil.java:181)

-- Texture being stitched together --
Details:
	Atlas path: textures
	Sprite: TextureAtlasSprite{name='openblocks:items/stencil-primer', frameCount=1, rotated=false, x=2864, y=864, height=16, width=16, u0=0.6992212, u1=0.70312256, v0=0.4218799, v1=0.4296826}
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:343)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:146)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:156)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 512119472 bytes (488 MB) / 1381302272 bytes (1317 MB) up to 17166499840 bytes (16371 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2297 Optifine OptiFine_1.10.2_HD_U_D2 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJA	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJA	openmodscore{0.11.1} [OpenModsLib Core] (minecraft.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJA	abyssalcraft{1.9.2.9} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.2.9.jar) 
	UCHIJA	animania{1.1.1} [Animania] (animania-1.10.2-1.1.1.jar) 
	UCHIJA	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJA	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJA	astralsorcery{1.3.2-beta} [Astral Sorcery] (astralsorcery-1.3.2-beta.jar) 
	UCHIJA	Baubles{1.3.3} [Baubles] (baubles-[1.10.2] 1.3.3.0.jar) 
	UCHIJA	betterfoliage{2.1.7} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.7.jar) 
	UCHIJA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJA	bouncing_balls{1.4.1} [Bouncing Balls] (BouncingBalls-1.9.4_1.10.x-1.4.1.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	UCHIJA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJA	double_jump{1.0.1} [DoubleJump] (DoubleJump-1.10.2-1.0.0.jar) 
	UCHIJA	lootablebodies{2.2.0} [DrCyano's Lootable Bodies] (DrCyanosLootableBodies_1.10.2-2.2.0.jar) 
	UCHIJA	dungeontactics{DT-0.11.0} [DungeonTactics] (dungeon-tactics-[1.10.2] 0.11.0.jar) 
	UCHIJA	grapplemod{1.10.2-v10} [Grappling hook mod] (grapplemod-1.10.2-v10.jar) 
	UCHIJA	grimoireofgaia{1.5.3} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.10.2-1.5.3.jar) 
	UCHIJA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.10.2.jar) 
	UCHIJA	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UCHIJA	ichunutil{6.4.0} [iChunUtil] (iChunUtil-1.10.2-6.4.0.jar) 
	UCHIJA	ionitems{1.0.0} [Ion Items] (IonItems-1.0.0.jar) 
	UCHIJA	ironchest{1.10.2-7.0.9.796} [Iron Chest] (ironchest-1.10.2-7.0.9.796.jar) 
	UCHIJA	journeymap{1.10.2-5.4.7} [JourneyMap] (journeymap-1.10.2-5.4.7.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	metamorph{1.1.2} [Metamorph] (metamorph-1.1.2-1.10.2.jar) 
	UCHIJA	openmods{0.11.1} [OpenModsLib] (OpenModsLib-1.10.2-0.11.1.jar) 
	UCHIJA	openblocks{1.7.1} [OpenBlocks] (OpenBlocks-1.10.2-1.7.1.jar) 
	UCHIJA	portalgun{6.0.1} [PortalGun] (PortalGun-1.10.2-6.0.1.jar) 
	UCHIJA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.10.2-2.0.5.jar) 
	UCHIJA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJA	simplecorn{2.2.0} [Simple Corn] (simpleCorn-1.10.2-2.2.0.jar) 
	UCHIJA	spartanshields{1.0} [Spartan Shields] (SpartanShields-1.10.2-1.0.jar) 
	UCHIJA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJA	telepads{1.10.2 v1.0} [Telepads] (telepads-1.10.2-1.0.0.0.jar) 
	UCHIJA	villagerinventory{1.0.3} [Villager Inventory Viewer] (VillagerInventory-1.10.2-1.0.3.jar) 
	Loaded coremods (and transformers): 
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.1.jar)
  openmods.core.OpenModsClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
llibrary (llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.7.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
AstralCore (astralsorcery-1.3.2-beta.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 5450'
	OpenModsLib class transformers: [pre_world_render_hook:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	Launched Version: 1.10.2-forge1.10.2-12.18.3.2297
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 5450 GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x AMD A6-6400K APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.10.2_HD_U_D2
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13399 Compatibility Profile Context 15.201.1151.1008
	OpenGlRenderer: AMD Radeon HD 5450
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2
```

**Comment by 0Chris0** [comment]
And before I added the Openblocks mod it wasn't crashing. This means the reason is the Openblocks mod!

sry for my BAD English

**Comment by boq** [comment]
The reason is Optifine. See #842, #841, #839, #835, #831, sp614x/optifine#787

**Comment by 0Chris0** [comment]
But optifine is really important for such a big Modpack. Can you change anything in the Config to fix this?

**Comment by boq** [comment]
No. Ask Optifine author when this will be fixed.
