### ISSUE TITLE
Block Placer crashes world when player steps in front of it

### ISSUE THREAD

**Issue by MigukNamja** [OpenMods/OpenBlocks#846]
java.lang.Error
    at java.lang.StrictMath.asin(Native Method)
    at java.lang.Math.asin(Math.java:189)
    at openmods.fakeplayer.UseItemAction.<init>(UseItemAction.java:37)
    at openblocks.common.tileentity.TileEntityBlockPlacer.doWork(TileEntityBlockPlacer.java:71)
    at openblocks.common.tileentity.TileEntityBlockManipulator.doWork(TileEntityBlockManipulator.java:72)
    at openblocks.common.tileentity.TileEntityBlockManipulator.func_145842_c(TileEntityBlockManipulator.java:57)
    at openmods.block.OpenBlock.func_189539_a(OpenBlock.java:447)

(Full crash report)[https://pastebin.com/r8aepd9Z]

**Comment by boq** [comment]
Umm, can you reproduce it? ` java.lang.StrictMath.asin` method shouldn't be able to throw Error, this seems more like broken coremod.
