### ISSUE TITLE
Random disconnects on 1.12.2

### ISSUE THREAD

**Issue by roboderpy** [OpenMods/OpenBlocks#857]
```
[09:25:23] [Netty Server IO #2/ERROR] [FML]: There was a critical exception handling a packet on channel autoreglib
java.lang.NullPointerException: null
        at java.util.EnumSet.typeCheck(Unknown Source) ~[?:1.8.0_152]
        at java.util.RegularEnumSet.add(Unknown Source) ~[?:1.8.0_152]
        at java.util.RegularEnumSet.add(Unknown Source) ~[?:1.8.0_152]
        at openmods.utils.SidedItemHandlerAdapter.getHandler(SidedItemHandlerAdapter.java:108) ~[SidedItemHandlerAdapter.class:?]
        at openblocks.common.tileentity.TileEntityAutoEnchantmentTable.getCapability(TileEntityAutoEnchantmentTable.java:238) ~[TileEntityAutoEnchantmentTable.class:?]
        at vazkii.quark.base.handler.DropoffHandler.getInventory(DropoffHandler.java:75) ~[DropoffHandler.class:?]
        at vazkii.quark.base.handler.DropoffHandler$Dropoff.findHandler(DropoffHandler.java:191) ~[DropoffHandler$Dropoff.class:?]
        at vazkii.quark.base.handler.DropoffHandler$Dropoff.locateItemHandlers(DropoffHandler.java:183) ~[DropoffHandler$Dropoff.class:?]
        at vazkii.quark.base.handler.DropoffHandler$Dropoff.execute(DropoffHandler.java:124) ~[DropoffHandler$Dropoff.class:?]
        at vazkii.quark.base.handler.DropoffHandler.dropoff(DropoffHandler.java:53) ~[DropoffHandler.class:?]
        at vazkii.quark.base.network.message.MessageDropoff.handleMessage(MessageDropoff.java:32) ~[MessageDropoff.class:?]
        at vazkii.arl.network.NetworkMessage.onMessage(NetworkMessage.java:57) ~[NetworkMessage.class:?]
        at vazkii.arl.network.NetworkMessage.onMessage(NetworkMessage.java:30) ~[NetworkMessage.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
        at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36) ~[SimpleChannelHandlerWrapper.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[SimpleChannelInboundHandler.class:?]
<...>
```

Happens mostly when coming into sight of auto enchanting table (moment where book opens)

**Comment by boq** [comment]
Fixed in  OpenModsLib
