### ISSUE TITLE
[CTD] When looking for @open in EJI

### ISSUE THREAD

**Issue by drakray** [OpenMods/OpenBlocks#877]
https://pastebin.com/J3m83kpF
`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at openblocks.client.renderer.item.stencil.StencilTextureManager$TexturePool$PoolTexture.upload(StencilTextureManager.java:96)
	at openblocks.client.renderer.TextureUploader.onRenderEnd(TextureUploader.java:31)`

**Comment by drakray** [comment]
client connected on a Ubuntu Server

**Comment by boq** [comment]
I have no idea what other mod messes with it (and why!?), but at least I made it harder to trigger.
