### ISSUE TITLE
Wrong use of FastTESR

### ISSUE THREAD

**Issue by HenryLoenwind** [OpenMods/OpenBlocks#909]
https://github.com/OpenMods/OpenBlocks/blob/1.12.X/src/main/java/openblocks/client/renderer/tileentity/TileEntitySprinklerRenderer.java#L41

That's not a FastTESR, that's a crash waiting to happen...

Ooops, it's not even waiting:

```
Caused by: java.lang.IllegalStateException: Already building!
    at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:291) ~[buk.class:?]
    at openblocks.client.renderer.tileentity.TileEntitySprinklerRenderer.renderTileEntityFast(TileEntitySprinklerRenderer.java:55) ~[TileEntitySprinklerRenderer.class:?]
    at openblocks.client.renderer.tileentity.TileEntitySprinklerRenderer.renderTileEntityFast(TileEntitySprinklerRenderer.java:23) ~[TileEntitySprinklerRenderer.class:?]
    at net.minecraftforge.client.model.animation.FastTESR.func_192841_a(FastTESR.java:58) ~[FastTESR.class:?]
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197) ~[bwx.class:?]
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192855_a(TileEntityRendererDispatcher.java:179) ~[bwx.class:?]
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(TileEntityRendererDispatcher.java:174) ~[bwx.class:?]
```

**Comment by boq** [comment]
Wow, that took only 9 months to notice. I'm guessing it's not often called via `func_192841_a`/`render`.
