### ISSUE TITLE
Vacuum Hopper Auto-Output Breaking

### ISSUE THREAD

**Issue by SuperKael** [OpenMods/OpenBlocks#944]
I am hosting an Enigmatica 2: Expert Skyblock server. This pack uses version 1.8 of OpenBlocks. Sometimes, at seemingly random, (possibly related to chunk reloads?) the Vacuum Hopper at my mob farm spits out an error, and then stops auto-outputting items. This is fixed by toggling the auto-output state of the respective side, which often results in the vacuum hopper auto-outputting while it doesn't visibly look like it should be (the little connector thing is toggled off on the vacuum hopper model.) Please note that I am not telling it to output exp anywhere, although for that matter the tank doesn't appear to be filling... at least it isn't visibly.

```
[Server thread/ERROR] [FML]: A TileEntity type openblocks.common.tileentity.TileEntityVacuumHopper has throw an exception trying to write state. It will not persist. Report this to the mod author
openmods.sync.SyncMap$SyncFieldException: Failed to sync field 'tank'
        at openmods.sync.SyncMapServer.write(SyncMapServer.java:98) ~[SyncMapServer.class:?]
        at openmods.sync.SyncMapServer.tryWrite(SyncMapServer.java:105) ~[SyncMapServer.class:?]
        at openmods.tileentity.SyncedTileEntity.func_189515_b(SyncedTileEntity.java:113) ~[SyncedTileEntity.class:?]
        at openblocks.common.tileentity.TileEntityVacuumHopper.func_189515_b(TileEntityVacuumHopper.java:295) ~[TileEntityVacuumHopper.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:382) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:691) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException: Null string not allowed
        at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_181]
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137) ~[fy.class:?]
        at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:107) ~[FluidStack.class:?]
        at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77) ~[FluidTank.class:?]
        at openmods.sync.SyncableTank.writeToNBT(SyncableTank.java:80) ~[SyncableTank.class:?]
        at openmods.sync.SyncMapServer.write(SyncMapServer.java:96) ~[SyncMapServer.class:?]
        ... 12 more
```

By the way, the typo in "has throw an exception" was not a mistake on my part... that's how it actually is in the console.

**Comment by boq** [comment]
Seems like fluid registration is broken. Can you load world and search in `debug.log` for word `xpjuice`?

**Comment by SuperKael** [comment]
The only mention of xpjuice is a few random things like 
`Registry: 8974 cyclicmagic:xpjuice net.minecraft.item.ItemBlock@545d0137`
and
`The fluid cyclicmagic:xpjuice has been selected as the default fluid for xpjuice`
Nothing that would suggest a problem. But anyway, after restarting the server for unrelated reasons, it appears to be working now ._.

**Comment by boq** [comment]
Yeah, that seem normal. Lines
```
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137) ~[fy.class:?]
        at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:107) ~[FluidStack.class:?]
```
suggest that somehow liquid was not registered (which should crash earlier), so I'm not sure what happened there. I checked Cyclic registration and it seems correct.
