### ISSUE TITLE
Conflict with Quark (r1.5-134) involving Quark's new "Totem of Holding"

### ISSUE THREAD

**Issue by fandomaniac** [OpenMods/OpenBlocks#947]
I have had the Open Blocks' Graves set to "false" in the config, because I use the Gravestones mod. I just updated to the latest Quark which just added a new gravestone-like feature called "Totem of Holding". This new feature seems to be interacting with (and activating)  Open Blocks graves, even when graves are set to "false" in the Open Blocks config. I have tried setting Totem of Holding to "false" in the Quark config, but it seems Open Blocks' graves are still active, even though graves are still set to "false" in the Open Blocks' config. It seems something in Quark is now over-riding the Open Blocks grave config.

I did submit an issue report with Vazkii (Quark dev), but wasn't sure if there was something you can also do to prevent Open Blocks graves config from being over-ridden by Quark or any other mod, when it is set to "false" in the Open Blocks config. 

Open Block version: 1.12.2-1.8
Quark Version:  r1.5-134 (latest release)
Forge Version: Forge-1.12.2 - 14.23.5.2769
```
05.12 09:57:17 [Server] Server thread/INFO [OpenMods]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:304): Storing post-mortem inventory into /./world2018/data/inventory-Kitryacatrya-2018-12-05_09.57.17-death-0.dat. It can be restored with command '/ob_inventory restore Kitryacatrya Kitryacatrya-2018-12-05_09.57.17-death-0'

05.12 09:57:17 [Server] Server thread/INFO [OpenMods]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:304): Storing post-mortem inventory into /./world2018/data/inventory-Kitryacatrya-2018-12-05_09.57.17-death-0.dat. It can be restored with command '/ob_inventory restore Kitryacatrya Kitryacatrya-2018-12-05_09.57.17-death-0'
05.12 09:57:17 [Server] Server thread/INFO Kitryacatrya was slain by Zombie
05.12 09:57:18 [Server] Server thread/WARN Keeping entity infernomobs:cephignis that already exists with UUID a603fedc-133d-4bec-873a-0ec8a0ff8469
05.12 09:57:20 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 2207ms behind, skipping 44 tick(s)
05.12 09:57:39 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 3312ms behind, skipping 66 tick(s)
05.12 09:59:28 [Server] Server thread/FATAL Error executing task
05.12 09:59:28 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 09:59:28 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
05.12 09:59:28 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
05.12 09:59:28 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
05.12 09:59:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
05.12 09:59:28 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 09:59:28 [Server] INFO at vazkii.quark.oddities.entity.EntityTotemOfHolding.func_85031_j(EntityTotemOfHolding.java:85) ~[EntityTotemOfHolding.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253) ~[aed.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425) ~[oq.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1090) ~[pa.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
05.12 09:59:28 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
05.12 09:59:28 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
05.12 09:59:28 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
05.12 09:59:28 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
05.12 09:59:28 [Server] INFO ... 5 more
05.12 10:00:41 [Server] Server thread/FATAL Error executing task
05.12 10:00:41 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:41 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
05.12 10:00:41 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
05.12 10:00:41 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
05.12 10:00:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
05.12 10:00:41 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:41 [Server] INFO at vazkii.quark.oddities.entity.EntityTotemOfHolding.func_85031_j(EntityTotemOfHolding.java:85) ~[EntityTotemOfHolding.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253) ~[aed.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425) ~[oq.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1090) ~[pa.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
05.12 10:00:41 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
05.12 10:00:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
05.12 10:00:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
05.12 10:00:41 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
05.12 10:00:41 [Server] INFO ... 5 more
05.12 10:00:45 [Server] Server thread/FATAL Error executing task
05.12 10:00:45 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:45 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
05.12 10:00:45 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
05.12 10:00:45 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
05.12 10:00:45 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
05.12 10:00:45 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:45 [Server] INFO at vazkii.quark.oddities.entity.EntityTotemOfHolding.func_85031_j(EntityTotemOfHolding.java:85) ~[EntityTotemOfHolding.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253) ~[aed.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425) ~[oq.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1090) ~[pa.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
05.12 10:00:45 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
05.12 10:00:45 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
05.12 10:00:45 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
05.12 10:00:45 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
05.12 10:00:45 [Server] INFO ... 5 more
05.12 10:00:49 [Server] Server thread/FATAL Error executing task
05.12 10:00:49 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:49 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
05.12 10:00:49 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
05.12 10:00:49 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
05.12 10:00:49 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
05.12 10:00:49 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:49 [Server] INFO at vazkii.quark.oddities.entity.EntityTotemOfHolding.func_85031_j(EntityTotemOfHolding.java:85) ~[EntityTotemOfHolding.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253) ~[aed.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425) ~[oq.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1090) ~[pa.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
05.12 10:00:49 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
05.12 10:00:49 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
05.12 10:00:49 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
05.12 10:00:49 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
05.12 10:00:49 [Server] INFO ... 5 more
05.12 10:00:50 [Server] Server thread/FATAL Error executing task
05.12 10:00:50 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:50 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_152]
05.12 10:00:50 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_152]
05.12 10:00:50 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
05.12 10:00:50 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
05.12 10:00:50 [Server] INFO Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemArmor.func_185083_B_()Lnet/minecraft/inventory/EntityEquipmentSlot;
05.12 10:00:50 [Server] INFO at vazkii.quark.oddities.entity.EntityTotemOfHolding.func_85031_j(EntityTotemOfHolding.java:85) ~[EntityTotemOfHolding.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1253) ~[aed.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1425) ~[oq.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1090) ~[pa.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
05.12 10:00:50 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
05.12 10:00:50 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_152]
05.12 10:00:50 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_152]
05.12 10:00:50 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
05.12 10:00:50 [Server] INFO ... 5 more
```

**Comment by fandomaniac** [comment]
It seems, changing "B:dumpDeadPlayersInventories=false" fixed this new issue caused by the Quark.

**Comment by boq** [comment]
This issue is not related in any way to OpenBlocks and option you have disabled is not related to graves.

Actualy problem is that TotemOfHolding calls client only method `ItemArmor.getEquipmentSlot` on server. This is definitely something that should be reported to author.
