### ISSUE TITLE
[1.12.2] Ticking player crash with the sleeping bag.

### ISSUE THREAD

**Issue by clockworkRocker** [OpenMods/OpenBlocks#955]
I get a -ticking player crash- when I try to sleep in the Sleeping Bag with Dark Chestplate from EnderIO on myself.

The crash report:
```
// Everything's going to plan. No, really, that was supposed to happen.

Time: 1/21/19 6:50 PM
Description: Ticking player

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.cosmicdan.sleepingoverhaul.common.eventhandlers.PlayerEvents.onPlayerSleepInBed(PlayerEvents.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1074_PlayerEvents_onPlayerSleepInBed_PlayerSleepInBedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerSleepInBed(ForgeEventFactory.java:527)
	at net.minecraft.entity.player.EntityPlayer.func_180469_a(EntityPlayer.java:1532)
	at net.minecraft.entity.player.EntityPlayerMP.func_180469_a(EntityPlayerMP.java:737)
	at openblocks.common.item.ItemSleepingBag.trySleep(ItemSleepingBag.java:113)
	at openblocks.common.item.ItemSleepingBag.onArmorTick(ItemSleepingBag.java:97)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:371)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at com.cosmicdan.sleepingoverhaul.common.eventhandlers.PlayerEvents.onPlayerSleepInBed(PlayerEvents.java:39)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1074_PlayerEvents_onPlayerSleepInBed_PlayerSleepInBedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerSleepInBed(ForgeEventFactory.java:527)
	at net.minecraft.entity.player.EntityPlayer.func_180469_a(EntityPlayer.java:1532)
	at net.minecraft.entity.player.EntityPlayerMP.func_180469_a(EntityPlayerMP.java:737)
	at openblocks.common.item.ItemSleepingBag.trySleep(ItemSleepingBag.java:113)
	at openblocks.common.item.ItemSleepingBag.onArmorTick(ItemSleepingBag.java:97)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:371)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 276
	Entity Name: _Silverring_
	Entity's Exact location: -439.68, 73.00, 365.07
	Entity's Block location: World: (-440,73,365), Chunk: (at 8,4,13 in -28,22; contains blocks -448,0,352 to -433,255,367), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@644f51a8
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1579997088 bytes (1506 MB) / 3569352704 bytes (3404 MB) up to 3569352704 bytes (3404 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2560m -Xmx3584m
	IntCache: cache: 0, tcache: 9, allocated: 0, tallocated: 92
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E2 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                | Version                  | Source                                        | Signature                                |
	|:--------- |:--------------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.5.2768             | forge-1.12.2-14.23.5.2768-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | openmodscore                      | 0.12.1                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | actuallyadditions                 | 1.12.2-r138              | ActuallyAdditions-1.12.2-r138.jar             | None                                     |
	| UCHIJAAAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCHIJAAAA | crafttweaker                      | 4.1.9                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCHIJAAAA | mtlib                             | 3.0.5                    | MTLib-3.0.5.jar                               | None                                     |
	| UCHIJAAAA | modtweaker                        | 4.0.13                   | modtweaker-4.0.13.jar                         | None                                     |
	| UCHIJAAAA | jei                               | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                     | None                                     |
	| UCHIJAAAA | botania                           | r1.10-356                | Botania+r1.10-356.jar                         | None                                     |
	| UCHIJAAAA | aiotbotania                       | 0.5                      | aiotbotania-0.5.jar                           | None                                     |
	| UCHIJAAAA | applecore                         | 3.1.3                    | AppleCore-mc1.12.2-3.1.3.jar                  | None                                     |
	| UCHIJAAAA | appliedenergistics2               | rv5-stable-11            | appliedenergistics2-rv5-stable-11.jar         | None                                     |
	| UCHIJAAAA | architecturecraft                 | @VERSION@                | architecturecraft-1.12-2.68.jar               | None                                     |
	| UCHIJAAAA | quark                             | r1.4-125                 | Quark-r1.4-125.jar                            | None                                     |
	| UCHIJAAAA | autoreglib                        | 1.3-18                   | AutoRegLib-1.3-18.jar                         | None                                     |
	| UCHIJAAAA | biomesoplenty                     | 7.0.1.2399               | BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
	| UCHIJAAAA | blur                              | 1.0.4-14                 | Blur-1.0.4-14.jar                             | None                                     |
	| UCHIJAAAA | ctm                               | MC1.12.2-0.3.2.18        | CTM-MC1.12.2-0.3.2.18.jar                     | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                  | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | cookingforblockheads              | 6.4.44                   | CookingForBlockheads_1.12.2-6.4.44.jar        | None                                     |
	| UCHIJAAAA | cosmiclib                         | 0.3.3                    | CosmicLib-1.12.2-0.3.3.ALPHA.jar              | d3974446c00f9f1d275edce305771eeddf30c658 |
	| UCHIJAAAA | ctgui                             | 1.0.0                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCHIJAAAA | crafttweakerjei                   | 2.0.2                    | CraftTweaker2-1.12-4.1.9.jar                  | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.37            | EnderCore-1.12.2-0.5.37.jar                   | None                                     |
	| UCHIJAAAA | enderio                           | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.87         | TConstruct-1.12.2-2.10.1.87.jar               | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.29                   | EnderIO-1.12.2-5.0.29.jar                     | None                                     |
	| UCHIJAAAA | extrabotany                       | 1.1                      | ExtraBotany-r1.1-31.jar                       | None                                     |
	| UCHIJAAAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.8.1.jar                    | None                                     |
	| UCHIJAAAA | forgemultipartcbe                 | 2.5.0.69                 | ForgeMultipart-1.12.2-2.5.0.69-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | microblockcbe                     | 2.5.0.69                 | ForgeMultipart-1.12.2-2.5.0.69-universal.jar  | None                                     |
	| UCHIJAAAA | minecraftmultipartcbe             | 2.5.0.69                 | ForgeMultipart-1.12.2-2.5.0.69-universal.jar  | None                                     |
	| UCHIJAAAA | hardcoredarkness                  | 2.0                      | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJAAAA | theoneprobe                       | 1.4.23                   | theoneprobe-1.12-1.4.23.jar                   | None                                     |
	| UCHIJAAAA | immersiveengineering              | 0.12-86                  | ImmersiveEngineering-0.12-86.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | immersivecables                   | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar              | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | itemscroller                      | 0.12.0                   | itemscroller-1.12.2-0.12.0.jar                | 2b03e1423915a189b8094816baa18f239d576dff |
	| UCHIJAAAA | harvestcraft                      | 1.12.2u                  | Pam's+HarvestCraft+1.12.2u.jar                | None                                     |
	| UCHIJAAAA | jehc                              | 1.12.2                   | JEHC-1.12.2-1.6.1.0.jar                       | None                                     |
	| UCHIJAAAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | loottweaker                       | 0.0.8                    | LootTweaker-1.12.2-0.0.8.jar                  | None                                     |
	| UCHIJAAAA | jeresources                       | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar       | None                                     |
	| UCHIJAAAA | levelup2                          | ${version}               | Level+Up!+2-1.1.22-1.12.jar                   | None                                     |
	| UCHIJAAAA | lostcities                        | 2.0.10                   | lostcities-1.12-2.0.10.jar                    | None                                     |
	| UCHIJAAAA | malisiscore                       | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UCHIJAAAA | malisisswitches                   | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar              | None                                     |
	| UCHIJAAAA | nei                               | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | openmods                          | 0.12.1                   | OpenModsLib-1.12.2-0.12.1.jar                 | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks                        | 1.8                      | OpenBlocks-1.12.2-1.8.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar             | None                                     |
	| UCHIJAAAA | redstoneflux                      | 2.0.2                    | RedstoneFlux-1.12-2.0.2.3-universal.jar       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | roots                             | 0.104                    | roots-2-0.104.jar                             | None                                     |
	| UCHIJAAAA | sereneseasons                     | 1.2.5                    | SereneSeasons-1.12.2-1.2.5-universal.jar      | None                                     |
	| UCHIJAAAA | tickratechanger                   | 1.0.14                   | TickrateChanger-1.0.14.jar                    | None                                     |
	| UCHIJAAAA | sleepingoverhaul                  | 0.1.2                    | SleepingOverhaul-1.12.2-0.1.2.BETA.jar        | d3974446c00f9f1d275edce305771eeddf30c658 |
	| UCHIJAAAA | spiceoflife                       | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                 | None                                     |
	| UCHIJAAAA | toughasnails                      | 3.1.0.115                | ToughAsNails-1.12.2-3.1.0.115-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.12.2-0.5.37.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.5-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
TickrateChanger (TickrateChanger-1.0.14.jar)
  me.guichaguri.tickratechanger.TickrateTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.3.3.ALPHA.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:ON, TESLA:OFF, CRAFTTWEAKER:ON
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['_Silverring_'/276, l='I got tired_', x=-439.68, y=73.00, z=365.07]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 391.25
	OpenGlRenderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
[18:50:48] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Program Files\MultiMC\instances\SA's Ecopunk- Post Human\.minecraft\crash-reports\crash-2019-01-21_18.50.47-server.txt
[18:50:48] [main/INFO] [FML]: Waiting for the server to terminate/save.
[18:50:48] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[18:50:48] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'I got tired_'/overworld
[18:50:48] [Netty Local Client IO #0/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[18:50:48] [Netty Local Client IO #0/INFO] [Tickrate Changer]: Updating server tickrate to 20.0
[18:50:48] [Netty Local Client IO #0/INFO] [Tickrate Changer]: Updating client tickrate to 20.0
[18:50:48] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'I got tired_'/ExtraUtils2_Quarry_Dim
[18:50:48] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'I got tired_'/Storage Cell
[18:50:48] [Server thread/INFO] [journeymap]: Mapping halted in C:\Program Files\MultiMC\instances\SA's Ecopunk- Post Human\.minecraft\journeymap\data\sp\I got tired_\DIM0
[18:50:50] [Server thread/INFO] [FML]: Unloading dimension 0
[18:50:50] [Server thread/INFO] [FML]: Unloading dimension -9999
[18:50:50] [Server thread/INFO] [FML]: Unloading dimension 2
[18:50:53] [Server thread/INFO] [FML]: Applying holder lookups
[18:50:53] [Server thread/INFO] [FML]: Holder lookups applied
[18:50:53] [Server thread/INFO] [Actually Additions]: Unloaded WorldData!
[18:50:53] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[18:50:53] [main/INFO] [FML]: Server terminated.
[18:50:53] [Client Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by boq** [comment]
It's incompatibility with SleepingOverhaul. This issue seems to be fixed in latest version.
