### ISSUE TITLE
XP Drain crash w/ OpenBlocks tank

### ISSUE THREAD

**Issue by duckfez** [OpenMods/OpenBlocks#977]
Similar crash to #974.  Overall modpack is "All the mods 3", so Mekanism https://github.com/mekanism/Mekanism/issues/5552 could be related as well.

Crash and debug logs at: https://gist.github.com/duckfez/95365a17a557a88db334c29e5176257d

```
[12:47:58] [Server thread/ERROR] [FML]: A TileEntity type openblocks.common.tileentity.TileEntityTank has throw an exception trying to write state. It will not persist. Report this to the mod author
openmods.sync.SyncMap$SyncFieldException: Failed to sync field 'tank'
        at openmods.sync.SyncMapServer.write(SyncMapServer.java:98) ~[SyncMapServer.class:?]
        at openmods.sync.SyncMapServer.tryWrite(SyncMapServer.java:105) ~[SyncMapServer.class:?]
        at openmods.tileentity.SyncedTileEntity.func_189515_b(SyncedTileEntity.java:113) ~[SyncedTileEntity.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:382) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_186027_a(ChunkProviderServer.java:230) [on.class:?]
        at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1007) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:408) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:446) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:579) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: java.lang.NullPointerException: Null string not allowed
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_222]
        at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
        at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138) ~[fy.class:?]
        at net.minecraftforge.fluids.FluidStack.writeToNBT(FluidStack.java:107) ~[FluidStack.class:?]
        at net.minecraftforge.fluids.FluidTank.writeToNBT(FluidTank.java:77) ~[FluidTank.class:?]
        at openmods.sync.SyncableTank.writeToNBT(SyncableTank.java:80) ~[SyncableTank.class:?]
        at openmods.sync.SyncMapServer.write(SyncMapServer.java:96) ~[SyncMapServer.class:?]
        ... 11 more
```

**Comment by boq** [comment]
Never had luck with reproducing that one, but maybe your `level.dat` might have some hints. Can you attach that?

**Comment by duckfez** [comment]
Be glad to, but so far it's not happened again in that same world.  After the server restart, I loaded in right back on top of the XP drain and it drained out into the tank immediately.  From there, subsequent uses have not caused a crash.  I will attempt some things to make reproduction more likely and update back.

**Comment by boq** [comment]
It's intermittent? Huh, very interesting. Anyway, it's seems less and less related to OpenBlocks (or Cyclic), both mods use this mechanism as expected. Actual problem is somewhere in Fluid registry itself (or some coremod that messes with it).

**Comment by duckfez** [comment]
Fair enough.  I'll attempt to run it down further and see if I can figure out the what/why
